### PR TITLE
Improve and refactor filtering

### PR DESCRIPTION
**Pull request by MarcAntoine-Arnaud**

### CODE REVIEW

**Comment by MarcAntoine-Arnaud** [comment]
@greyblake When you have time you can check.
I update to manage filtering in a more generic way.

**Comment by greyblake** [comment]
@MarcAntoine-Arnaud Thank you)

**Comment by greyblake** [comment]
@MarcAntoine-Arnaud Hey, thanks for your activity.
I really apologize for postponing this that much. Just to let you know, I keep an eye on it.

**Comment by MarcAntoine-Arnaud** [comment]
No problem, I still have few fixes to improve filter with most options supported.

**Comment by greyblake** [comment]
@MarcAntoine-Arnaud thanks for your contribution. I have some time today, will try to continue based on your work.

One note regarding long term vision: at some point I'd like to introduce mutable iterators, so items can be mutate or deleted, at the moment it's not possible.

**Pull request merged**
